site_name: VITA
site_description: VITA â€“ Voice Integration Toolkit for Applications. Modular, lightweight TTS with Kokoro-82M and Bark.
site_url: https://moulish-dev.github.io/shadcn-vita/
repo_url: https://github.com/moulish-dev/vita
repo_name: moulish-dev/vita

theme:
  name: shadcn
  logo: images/vita_logo.ico
  favicon: images/vita_logo.ico
  show_title: true
  show_stargazers: true
  icon: heroicons:megaphone
  topbar_sections: false
  pygments_style:
    light: shadcn-light
    dark: github-dark

nav:
  - Home: index.md
  - Quick Start: quick-start.md
  - Install: install.md
  - Usage: usage.md
  - Models: models.md
  - System Requirements: system-requirements.md
  - Examples: examples.md
  - CLI: cli.md
  - Roadmap: roadmap.md
  - Contibutions: contributing.md
  - FAQ: faq.md
  - Acknowledgements: acknowledgements.md
  - License: license.md

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - codehilite
  - shadcn.extensions.codexec
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.inlinehilite

#analytics (uncomment one)
extra:
  analytics:
    provider: google
    property: G-0R6PK81L2X
extra_javascript:
  - https://plausible.io/js/script.js
